version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "9090:8080"  # Change the exposed port from 8080 to 9090
    volumes:
      - "C:/Users/geostn/Desktop/Mine/PhD/Artificial Intelligence Cloud Computing/Mod 3/PE03/Jenkins:/var/jenkins_home" 
      - JENKINS_OPTS=--httpPort=8080
